"""Backend protocol: the model never touches KiCad APIs directly."""

from typing import Protocol


class Backend(Protocol):
    def read_footprints(self): ...
    def move_footprints(self, snaps): ...
    def clear_generated(self): ...
    def write_tracks(self, pieces, width_nm: int): ...
    def write_cut_markers(self, cuts): ...
    def place_links(self, links): ...
    def save(self): ...
