# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Somerled Design
"""Where the StripForge footprint library and DRC rules live, and checks on the rules file.

The library (``footprints/StripForge.pretty``, nickname ``StripForge``) and the custom rules
(``rules/stripforge.kicad_dru``) are Mildrew's, kept at the top of the repository. They are found
in this order: an explicit path, then the ``STRIPFORGE_LIBRARY`` / ``STRIPFORGE_RULES`` environment
variables, then the repository checkout that this package runs from (an editable install).

The rules file is generated by ``rules/gen_dru.py --strip-width <w>``: whenever
``strip_width_mm`` changes in the config, regenerate it, or DRC rule "SF strip width" flags every
strip. :func:`check_rules_width` warns when the two disagree.
"""

from __future__ import annotations

import os
import re
from pathlib import Path

LIB_NICKNAME = "StripForge"
REPO_ROOT = Path(__file__).resolve().parents[2]
_REGEN = "regenerate it with: python3 rules/gen_dru.py --strip-width {w}"


def _find(explicit: str | Path | None, env: str, default: Path, what: str) -> Path:
    for cand in (explicit, os.environ.get(env)):
        if cand:
            p = Path(cand)
            if not p.exists():
                raise FileNotFoundError(f"{what} not found: {p}")
            return p
    if default.exists():
        return default
    raise FileNotFoundError(
        f"{what} not found (looked for {default}); pass its path or set {env} "
        "(it lives in the StripForge repository)"
    )


def library_dir(explicit: str | Path | None = None) -> Path:
    """The ``StripForge.pretty`` footprint library directory."""
    return _find(
        explicit, "STRIPFORGE_LIBRARY", REPO_ROOT / "footprints" / "StripForge.pretty", "footprint library"
    )


def rules_file(explicit: str | Path | None = None) -> Path:
    """The ``stripforge.kicad_dru`` custom DRC rules file."""
    return _find(explicit, "STRIPFORGE_RULES", REPO_ROOT / "rules" / "stripforge.kicad_dru", "DRC rules file")


def footprint_file(name: str, library: str | Path | None = None) -> Path:
    """Path of ``<name>.kicad_mod`` (``Link_P7.62``, ``CUT_Hole``) in the library."""
    p = library_dir(library) / f"{name}.kicad_mod"
    if not p.exists():
        raise FileNotFoundError(f"footprint {LIB_NICKNAME}:{name} not found in {p.parent}")
    return p


_WIDTH_RE = re.compile(
    r'\(rule\s+"SF strip width".*?\(constraint\s+track_width\s+\(min\s+([\d.]+)\s*mm\)',
    re.DOTALL,
)


def dru_strip_width(text: str) -> float | None:
    """The strip width (mm) that rule "SF strip width" enforces, or None if the rule is missing."""
    m = _WIDTH_RE.search(text)
    return float(m.group(1)) if m else None


def check_rules_width(dru_text: str, strip_width_mm: float) -> list[str]:
    """Warnings if the rules file's strip width differs from the config's ``strip_width_mm``."""
    w = dru_strip_width(dru_text)
    if w is None:
        return ['rules: no "SF strip width" rule found in the .kicad_dru; ' + _REGEN.format(w=strip_width_mm)]
    if abs(w - strip_width_mm) > 1e-6:
        return [
            f"rules: the .kicad_dru enforces a {w:g} mm strip width but the config's strip_width_mm is "
            f"{strip_width_mm:g} mm, so DRC will flag every strip; " + _REGEN.format(w=f"{strip_width_mm:g}")
        ]
    return []
