#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Somerled Design
"""Generate rules/stripforge.kicad_dru, StripForge's custom KiCad 10 DRC rules.

Owner: Mildrew (EE). See rules/README.md and Sketch.md section 4.6.

These rules are ONLY stripboard hygiene. They never decide whether two nets may share a strip:
that is KiCad's built-in "Items shorting two nets" / unconnected-items / parity checks.

KiCad reads custom rules from ``<board-name>.kicad_dru`` next to the ``.kicad_pro``/``.kicad_pcb``,
so copy (or have the writer copy) this file to that name.

Usage:
    python3 rules/gen_dru.py [--strip-width 1.8] [--edge-clearance 0.1] [--out rules/stripforge.kicad_dru]

--strip-width must equal the ``strip_width_mm`` the writer draws strips with (stripboard.toml).
The default, 1.8 mm, is Kevin's caliper measurement of his X56 board (2026-09-27).
"""

from __future__ import annotations

import argparse
from pathlib import Path

PITCH = 2.54

TEMPLATE = """\
(version 1)
# StripForge custom DRC rules (generated by rules/gen_dru.py; do not edit by hand).
# Stripboard hygiene only. Net sharing is caught by KiCad's built-in checks
# (shorting_items, unconnected_items, schematic parity), never by these rules.
# NOTE: kicad-cli pcb drc does NOT report errors in this file; a bad condition silently disables
# rules. Verify changes with tests/test_stripforge_rules.py (mutation tests), not by "it ran".
# Parameters: pitch {pitch} mm, strip width {w} mm (strip-to-strip gap as drawn {gap} mm; 1.8 mm is
# the caliper-measured strip width of the X56 board, 2026-09-27),
# strip/pad to board-edge clearance {edge} mm.

# 1. Strips are B.Cu tracks of exactly the strip width. Anything else on B.Cu is not stripboard.
(rule "SF strip width"
    (layer "B.Cu")
    (condition "A.Type == 'Track'")
    (constraint track_width (min {w}mm) (opt {w}mm) (max {w}mm)))

# 2. Stripboard has no copper tracks on the component side: links are W footprints, not tracks.
(rule "SF no F.Cu tracks"
    (layer "F.Cu")
    (constraint disallow track))

# 3. Single-sided board: no vias of any kind.
(rule "SF no vias"
    (constraint disallow via micro_via buried_via))

# 4. No copper zones/pours: the only copper is the strips.
(rule "SF no copper zones"
    (layer outer)
    (constraint disallow zone))

# 5. Parts go on the component side. A footprint flipped to B.Cu would be built mirrored.
(rule "SF no back-side footprints"
    (layer "B.Cu")
    (constraint disallow footprint))

# 6. Real strips run to the board edge, and the outer holes sit half a pitch (1.27 mm) in, so a
#    {w} mm strip is {edge_row} mm from Edge.Cuts and a 1.7 mm pad in an edge hole 0.42 mm: both
#    under KiCad's default 0.5 mm copper-to-edge clearance. Relax it for tracks and pads only.
(rule "SF strip and pad edge clearance"
    (condition "A.Type == 'Track' || A.Type == 'Pad'")
    (constraint edge_clearance (min {edge}mm)))

# 7. (Not enabled, untested template.) Pad-to-neighbouring-strip clearance relaxation. With a
#    {w} mm strip, the largest pad that still clears the next strip by KiCad's default 0.2 mm is
#    {maxpad} mm across the strip; every pad on the ATtiny10 TPI fixture is <= 2.435 mm, so none
#    is needed. A custom rule cannot go below Board Setup's minimum clearance, so that minimum
#    would have to be lowered in the project as well. Example (fill in the reference):
# (rule "SF big pad to neighbour strip"
#     (condition "A.Type == 'Pad' && B.Type == 'Track' && A.memberOfFootprint('F1')")
#     (constraint clearance (min 0.15mm)))

# 8. Dangling dead-copper strips: KiCad's "track_dangling" check has no .kicad_dru constraint;
#    its severity lives in the project file (rule_severities.track_dangling in .kicad_pro).
"""


def render(strip_width: float, edge: float) -> str:
    def f(v: float) -> str:
        return f"{v:.3f}".rstrip("0").rstrip(".")

    return TEMPLATE.format(
        pitch=f(PITCH),
        w=f(strip_width),
        gap=f(PITCH - strip_width),
        edge=f(edge),
        edge_row=f(PITCH / 2 - strip_width / 2),
        maxpad=f(2 * (PITCH - strip_width / 2 - 0.2)),
    )


def main() -> None:
    here = Path(__file__).resolve().parent
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument(
        "--strip-width",
        type=float,
        default=1.8,
        help="must equal stripboard.toml strip_width_mm "
        "(1.8 mm: caliper measurement of the X56 board, 2026-09-27)",
    )
    ap.add_argument("--edge-clearance", type=float, default=0.1)
    ap.add_argument("--out", type=Path, default=here / "stripforge.kicad_dru")
    a = ap.parse_args()
    if not 0 < a.strip_width < PITCH:
        ap.error("strip width must be between 0 and the pitch")
    a.out.write_text(render(a.strip_width, a.edge_clearance), encoding="utf-8")
    print(a.out)


if __name__ == "__main__":
    main()
